### PR TITLE
[showcase][xs]: update R instruction for Linux machines

### LINKED ISSUE #209: Instructions for R is failing on Linux
Originally comes from here https://github.com/datahq/datahub-qa/issues/115

You might get following error if you're using Linux 
```
Warning in install.packages("jsonlite") :
  'lib = "/usr/local/lib/R/site-library"' is not writable
Error in install.packages("jsonlite") : unable to install packages
```

## Acceptance Criteria 

* [ ] Following the Instructions on datahub/publisher/package for R should print data

## Tasks 

* [ ] find the reason
* [ ] update the isntrutions 

## Analysis

Following this blog post https://www.r-bloggers.com/installing-r-packages/ 

> `install.packages("jsonlite")`
> In theory the package should just install, however:
> * if you are using Linux and don’t have root access, this command won’t work.
> * you will be asked to select your local mirror, i.e. which server should you use to download the package.

This issue is fixed if you try and run scripts with root permission. However, I'm getting following
```
Error in contrib.url(repos, type) : 
  trying to use CRAN without setting a mirror
```

No errors are produced  if you specify package repository. For instance, this works perfectly if you run with sudo

```
install.packages("jsonlite", repos="https://cran.rstudio.com/")
library("jsonlite")

json_file <- 'https://datahub.io/core/finance-vix/datapackage.json'
json_data <- fromJSON(paste(readLines(json_file), collapse=""))

# get list of all resources:
print(json_data$resources$name)

# print all tabular data(if exists any)
for(i in 1:length(json_data$resources$datahub$type)){
  if(json_data$resources$datahub$type[i]=='derived/csv'){
    path_to_file = json_data$resources$path[i]
    data <- read.csv(url(path_to_file))
    print(data)
  }
}

```

### PR DESCRIPTION
**Pull request by zelima**
* define repo parameter for install
* Notify to use `sudo`.

fixes #209

### CODE REVIEW

**Comment by zelima** [comment]
@AcckiyGerman Why do you think that this is better than just run script with sudo. Don't think it's a good Idea to split out installation instructions - more text to write, more instructions to read, more stuff to install... Also, it's only for Linux users. Why should we complicate when we can just say the should run with `sudo`

**Comment by AcckiyGerman** [comment]
@zelima yes, you right, let's remove `sudo` as we have warning about it (I didn't think about macOS\win users)

The reason to split instructions into "install libs" and "run script" is that user need to install the lib|package only once.
The 'get data' script then could be executed many times, and we don't need to install the libs for every run.

> more text to write, more instructions to read, more stuff to install

+ 1 line of text
+ we add some structure
+ we need to install the lib anyway, so why to install it every script run?
+ we have the same instructions structure in python and node sections.

**Comment by AcckiyGerman** [comment]
@zelima but you are right only in the case, when user creates a script for distribution - then including the `install lib` in the script have sence

**Comment by AcckiyGerman** [comment]
@zelima anyway it is not the big deal - any user could understand the difference, if he's able to run scripts, so I'm approving your changes, and you decide leave script or split it.

**Comment by zelima** [comment]
@AcckiyGerman Great. Don't think we care user installs aside package once or now - let's leave that for them to decide

**Pull request merged**
